# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/kjaymiller/frontmatter-check
    rev: 2025.5.1b2
    hooks:
      - id: frontmatter-check
        name: Check frontmatter in markdown files
        description: Validates frontmatter in markdown files
        entry: frontmatter-check
        types: [markdown]
